George/ffs 1147 confirmation number
DSACMS/iv-cbv-payroll pull request #111
Opened 2024-07-22 18:10 UTC by GeorgeCodes19

## Ticket

Resolves [FFS-1147](https://jiraent.cms.gov/browse/FFS-1147)

## Changes

- Added `confirmation_number` to `cbv_flow` table
- Added a `show` method to the `Successes Controller` which generates and persists a `confirmation_number` on the `cbv_flow` table. 
- Added Tests

## Context for reviewers
Technically I've generated a confirmation code rather than number. The code is prefixed with the ID of the `cbv_flow`. I'm not 100% happy with this decision, but it helps to avoid creating a truly unique code that isn't a UUID. I want to go with something that's human readable.

<img width="1033" alt="Screenshot 2024-07-22 at 2 09 56 PM" src="https://github.com/user-attachments/assets/4940f3d1-d870-44eb-b603-2e3d46cf771a">

2024-07-22 18:15 UTC, GeorgeCodes19 commented on app/app/controllers/cbv/successes_controller.rb
> +    confirmation_number = "#{@cbv_flow.id}-#{Time.now.to_i.to_s(36)}"
`.to_i..to_s(36)` converts the Unix timestamp to an integer (representing seconds) since epoch. It then converts the timestamp integer to a base-36 string. Base-36 uses the characters `0-9` and `a-z` to represent numbers, which makes the string more compact than a base-10 representation.

2024-07-22 18:16 UTC, GeorgeCodes19 commented on app/app/controllers/cbv/successes_controller.rb
> +    confirmation_number = "#{@cbv_flow.id}-#{Time.now.to_i.to_s(36)}"
How do we feel about exposing the internal table ID here?

2024-07-22 19:51 UTC, GeorgeCodes19 commented on app/app/controllers/cbv/successes_controller.rb
> +      prefix = session[:state]
I presume that the resolved state partner config will be stored in the session after the initial page load. I'm not sure if that would be nested under a config option. For now we can infer the state partner from the the top-level session object.

2024-07-22 21:53 UTC, tdooner requested changes
Sorry but I do think the "which controller should generate the confirmation number" question is a blocker here because this implementation would prevent us from putting it on the PDF sent to the caseworker on the previous page. Looks good to me after that is addressed.

2024-07-22 21:53 UTC, tdooner commented on app/app/controllers/cbv/successes_controller.rb
> +    confirmation_number = "#{@cbv_flow.id}-#{Time.now.to_i.to_s(36)}"
A couple pieces of feedback on this, based on my experience on other projects:
1. IMHO, exposing the ID is fine as long as the confirmation number includes some other harder-to-guess elements (which it does, with the encoded timestamp). The only issue I see here is that the length of the confirmation number will change as the project grows. It's not exactly necessary for conf numbers to always be the same length but it can be a nice property to have.
2. The Base-36 encoding is an interesting idea. I kind of like it. The only problem with alphanumeric is that we should consider normalizing characters that might be mistaken for each other, e.g. `O` and `0`, `I` and `1`, etc.

With that I think I'd recommend a slightly-tweaked generation approach:

```ruby
  # produce a confirmation number like "NY28J0123" representing a NY prefix, a
  # timestamp "28J", and a CBV flow ID of 123.
  confirmation_number = [
    prefix,
    (Time.now.to_i % 36 ** 3).to_s(36).upcase.tr("OISB", "0158").rjust(3, "0"),
    @cbv_flow.id.to_s.rjust(4, "0"),
  ].compact.join
```

2024-07-22 21:53 UTC, tdooner commented on app/app/controllers/cbv/successes_controller.rb
>        @cbv_flow.update(confirmation_number: confirmation_number)
There's a couple issues with doing this in the successes controller:

1) It won't be present at the time we send the PDF to the caseworker on the previous page. Ideally, we would include the confirmation number on the PDF that we send to the caseworker as well.
2) It's unidiomatic to do data updates in a `GET` / `show` action since GET actions are typically considered idempotent.

To me those both point towards proposing you move this to the `Cbv::SharesController` `#update` method since that's the action that most closely represents the idea of the cbv flow results being "confirmed" by the applicant.

2024-07-22 21:53 UTC, tdooner commented on app/app/controllers/cbv/successes_controller.rb
> +      prefix = session[:state]
I was thinking it'd be stored in the `@cbv_flow` object in the session, i.e. `@cbv_flow.site_id`. For now this will work, and then I'll go through and refactor this once we actually have the field on the `@cbv_flow` object.

2024-07-22 21:53 UTC, tdooner commented on app/app/controllers/cbv/successes_controller.rb
> +  end
Why? `@cbv_flow` should be accessible in the view.

2024-07-24 16:13 UTC, GeorgeCodes19 commented on app/app/controllers/cbv/successes_controller.rb
> +    confirmation_number = "#{@cbv_flow.id}-#{Time.now.to_i.to_s(36)}"
Awesome. After reading your response I pictured something like this.

2024-07-24 20:51 UTC, GeorgeCodes19 commented on app/app/controllers/cbv/shares_controller.rb
> +    ].compact.join.upcase
Added a call to `upcase` to ensure that the confirmation codes are all caps.

2024-07-25 00:55 UTC, tdooner approved these changes
Looks good. Please remove the old `confirmation_number` column from the db/schema.rb file before merging.

2024-07-25 00:55 UTC, tdooner commented on app/app/controllers/cbv/shares_controller.rb
> +    ].compact.join.upcase
Cool, good idea. We could remove the `upcase` from the middle chunk then.
<img width="180" alt="image" src="https://github.com/user-attachments/assets/3219dfe9-188f-4553-8fa9-8285d8db9736">

2024-07-25 00:55 UTC, tdooner commented on app/db/schema.rb
> +    t.string "confirmation_number"
Changing migrations after they are run is tricky business - you have to run `rails db:rollback` before changing the migration so it'll delete the old column. Since your local database is in a weird state, you should fix it by dropping the old `confirmation_number` column and then removing this line from the db/schema.rb file.

2024-07-25 00:55 UTC, tdooner commented on app/spec/controllers/cbv/shares_controller_spec.rb
> +        expect(cbv_flow.reload.confirmation_code).to eq(existing_confirmation_code)
Fun rspec tip, they have a shorthand for this that you may see elsewhere:

```ruby
expect do
  put :update
end.not_to change { cbv_flow.reload.confirmation_code }
```

2024-07-25 22:28 UTC, merged