Updates to the Add Job Page
DSACMS/iv-cbv-payroll pull request #125
Opened 2024-07-31 21:50 UTC by GeorgeCodes19

## Ticket

Resolves FFS-1140

## Changes

- Added translations for the add_job page copy
- Added a slim [alert component](https://designsystem.digital.gov/components/alert/) from the USWDS component library
- Redirecting to `employer_search` if the user has additional jobs, otherwise redirecting to the `summary` page.
## Context for reviewers
<img width="531" alt="Screenshot 2024-08-07 at 2 39 16 PM" src="https://github.com/user-attachments/assets/ee0e20d0-fbbd-4abc-ac63-cae6db299e2a">

2024-07-31 21:59 UTC, GeorgeCodes19 commented on app/app/javascript/controllers/cbv/add_job.js
> +    console.log("Add job controller connected");
Mental note to remove this

2024-08-06 00:50 UTC, tdooner commented
@GeorgeCodes19 I rebased this branch and [cleaned up a couple things](https://github.com/DSACMS/iv-cbv-payroll/pull/125/commits/53de8dbc847263548eb7a650519afa6034da1fbf). The designs have changed now for this page - when you're back, can you take another look and finish implementation based on the new designs? I think the JS will be unnecessary now.

2024-08-07 16:14 UTC, GeorgeCodes19 commented
> @GeorgeCodes19 I rebased this branch and [cleaned up a couple things](https://github.com/DSACMS/iv-cbv-payroll/pull/125/commits/53de8dbc847263548eb7a650519afa6034da1fbf). The designs have changed now for this page - when you're back, can you take another look and finish implementation based on the new designs? I think the JS will be unnecessary now.

Noted!

2024-08-07 16:50 UTC, GeorgeCodes19 commented on app/app/controllers/cbv/add_jobs_controller.rb
> +      flash[:slim_alert] = { message: t(".notice_no_answer"), type: "error" }
I made this a bit dynamic so that we can toggle between the different USWDS alert "types".

2024-08-07 17:20 UTC, GeorgeCodes19 commented on app/app/views/cbv/add_jobs/show.html.erb
> +<% day_count = "90" %>
I'm wondering if this should be in the `site_config`

2024-08-07 17:51 UTC, GeorgeCodes19 commented on app/app/controllers/cbv/add_jobs_controller.rb
> +      flash[:slim_alert] = { message: t(".notice_no_answer"), type: "error" }
It's a [USWDS alert component ](https://designsystem.digital.gov/components/alert/)without the header. 

```html
<div class="usa-alert usa-alert--info usa-alert--slim">
  <div class="usa-alert__body">
    <p class="usa-alert__text">
      Lorem ipsum dolor sit amet,
      <a class="usa-link" href="javascript:void(0);">consectetur adipiscing</a>
      elit, sed do eiusmod.
    </p>
  </div>
</div>
```

<img width="938" alt="Screenshot 2024-08-07 at 1 49 33 PM" src="https://github.com/user-attachments/assets/e7df61d2-3b3a-4c09-92ae-36cd08d47a91">

2024-08-07 18:27 UTC, carmenrosalop requested changes
Looks good! Here are a few things that need updating:
- Add a colon (:) after text "Answer YES if your job" and "Answer no if" 
- Radio buttons should be updated with this text:
"Yes, I have another job that meets the criteria"
"No, I don’t have another job that meets the criteria"
- Spacing between the last radio button and the "Continue" button should be token 5 or 40px https://designsystem.digital.gov/design-tokens/spacing-units/

2024-08-07 18:27 UTC, GeorgeCodes19 commented on app/app/views/cbv/add_jobs/show.html.erb
> +<% day_count = "90" %>
Moved to site_config

2024-08-07 19:17 UTC, carmenrosalop approved these changes
LGTM! Thank you! 
FYI in a future site-wide ticket we will have an AC to update the line height https://designsystem.digital.gov/design-tokens/typesetting/line-height/ of the body text so that there is more space between the lines, but this implementation looks good!

2024-08-07 21:08 UTC, merged