Dynamically resolve the applicant (CBV) invite form based on site_id
DSACMS/iv-cbv-payroll pull request #150
Opened 2024-08-07 21:52 UTC by GeorgeCodes19

## Ticket

[FFS-1020](https://jiraent.cms.gov/browse/FFS-1020)

## Changes

- Infer the `site_id` from the params when loading the new invitation page, making it accessible to the responsible view handler.
- Update the view to load applicable state invitation form based on the `site_id`

## Context for reviewers

> Testing instructions, background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.

## Testing

<img width="608" alt="Screenshot 2024-08-07 at 5 49 24 PM" src="https://github.com/user-attachments/assets/1523546d-4721-4e00-8349-f94fb19eabfb">
<img width="573" alt="Screenshot 2024-08-07 at 5 49 31 PM" src="https://github.com/user-attachments/assets/c478767f-99ab-405a-8f48-a33852ccfda3">

2024-08-07 23:13 UTC, GeorgeCodes19 commented on app/app/controllers/cbv_flow_invitations_controller.rb
> +    site_id.to_s.gsub(/\A\//, '').gsub(/\A\.\.\//, '').gsub(/\/\.\.\//, '/')
Because `site_id` is used in a view to read a partial. This is just being particular about not allowing the `site_id` to have a leading `/` or `../` (or combination of) and enabling a malicious user to load .erb templates and partials since the project structure is public (open source)

2024-08-08 18:52 UTC, tdooner reviewed
How did you make the database changes? Did you add all these as columns to `cbv_flow_invitations` table?

2024-08-08 18:52 UTC, tdooner commented on app/app/controllers/cbv_flow_invitations_controller.rb
> +    site_id.to_s.gsub(/\A\//, '').gsub(/\A\.\.\//, '').gsub(/\/\.\.\//, '/')
Why is checking the site ID is specified in the configuration file not sufficient here? If an attacker tried directory traversal, it would just fail the check since "../../../../../../../etc/passwd" is not a site we've configured in the YAML file... right?

2024-08-08 18:52 UTC, tdooner commented on app/spec/controllers/cbv_flow_invitations_controller_spec.rb
> +          expect(response.body).to include("snap_application_date")
I don't think `hash_including` will work because `response.body` isn't a hash, it's a string. I don't mind the repeated `include` statements, personally.

2024-08-08 18:52 UTC, tdooner commented on app/spec/controllers/cbv_flow_invitations_controller_spec.rb
> +  let(:ma_params) { { site_id: "ma", secret: invite_secret } }
FYI - we can remove the `invite_secret` bits from the test since we no longer use that for authentication. (We are using the `sign_in user` on line 40)

2024-08-08 18:52 UTC, tdooner commented on app/spec/controllers/cbv_flow_invitations_controller_spec.rb
> +  # hoisted here so that it's accessible to the test suite hooks .e.g. "before"
This comment appears to be incorrect - each test case is specifying `site_id` separately.

2024-08-08 21:01 UTC, GeorgeCodes19 commented
> How did you make the database changes? Did you add all these as columns to `cbv_flow_invitations` table?

Please refer to the PR description. I wanted to separate the view and data persistence.

2024-08-08 21:04 UTC, GeorgeCodes19 commented on app/app/controllers/cbv_flow_invitations_controller.rb
> +    site_id.to_s.gsub(/\A\//, '').gsub(/\A\.\.\//, '').gsub(/\/\.\.\//, '/')
Sure, either way we'll need a separate method rather than pulling the site_id directly from the params to satisfy the Brakeman check.

2024-08-08 22:21 UTC, tdooner commented
> I wanted to separate the view and data persistence.

Ah my bad, sorry for missing that in your description. I don't think it will work to split it into two PRs, though, as Rails requires the database fields to be present in order to render the form fields. You could add all the database fields in the first PR, I guess, but it's probably just easiest to do it all in one PR.

2024-08-09 03:29 UTC, GeorgeCodes19 commented on app/config/locales/en.yml
> +        first_name: First name
Whoops, overlooked these locales. A few should mirror the nyc locales (first_name, middle_name, last_name, email_address). It would great to eventually move some of these to shared namespace.

2024-08-09 03:32 UTC, GeorgeCodes19 commented on app/spec/controllers/cbv_flow_invitations/auth_spec.rb
> +        .with(ActionController::Parameters.new(email_address: "test@example.com", case_number: "ABC1234", site_id: site_id).permit!)
There's some code duplication that can be cleaned up.

2024-08-09 03:36 UTC, GeorgeCodes19 commented on app/spec/controllers/cbv_flow_invitations/nyc_spec.rb
> +        first_name: "John",
This looks like it's missing the `CIN` field

2024-08-09 16:56 UTC, carmenrosalop requested changes
Looks good! 
There are 3 small things that need updating:
- When the calendar opens, it should look like this screenshot (closer to the component). Right now it's a bit far and floating
- I'd remove the word "Format" from the hint text "mm/dd/yyyy" because in other hint texts we won't add that word so we can keep it consistent
- Spacing between the "SNAP application date", hint text "mm/dd/yyyy" and the calendar should be corrected to look like the screenshot


![Screenshot 2024-08-09 at 9 46 05 AM](https://github.com/user-attachments/assets/c2988a7f-3923-4177-80b2-ef9302172e1c)

2024-08-09 17:23 UTC, tdooner approved these changes
Looks good to me, pending removal of the coercion to a regular hash (or an explanation of why it's necessary). ~Please pair with Carmen and run it by her before merging!~ Never mind I see she weighed in above.

2024-08-09 17:23 UTC, tdooner commented on app/spec/controllers/cbv_flow_invitations/nyc_spec.rb
> +    end
The ruby community is very opinionated that 2-space indents are the way to go. We could update rubocop to just do it for us automatically.

2024-08-09 17:23 UTC, tdooner commented on app/spec/controllers/cbv_flow_invitations/nyc_spec.rb
> +        first_name: "John",
CIN = `client_id_number` doesn't it? I see it below.

2024-08-09 21:44 UTC, carmenrosalop commented
@GeorgeCodes19 I just caught this now, the text under the H1 needs to be updated. See image ![image](https://github.com/user-attachments/assets/de118c24-9fd8-4a33-ae78-d2eff9935ade)

2024-08-09 22:53 UTC, carmenrosalop approved these changes
LGTM!

2024-08-12 17:37 UTC, merged