1021: Implement org-specific applicant emails, extract caseworker mailer out
DSACMS/iv-cbv-payroll pull request #152
Opened 2024-08-08 00:53 UTC by allthesignals

## Ticket

Resolves [1021](https://jiraent.cms.gov/browse/FFS-1021)

## Changes

Splits up caseworker mailer into its own mailer
Adds org-specific styling to each email

<img width="721" alt="image" src="https://github.com/user-attachments/assets/f98f8b5d-7d26-4cb8-9d77-00fa91faabf2">

2024-08-08 18:57 UTC, GeorgeCodes19 commented on app/spec/mailers/applicant_mailer_spec.rb
> +  let(:cbv_flow_invitation) { CbvFlowInvitation.create(email_address: email, site_id: 'nyc') }
I'm not sure how I feel about making site specific test cases. I was under the impression that we would prioritize nyc deliverables over ma, but not alter the codebase to be tailored towards one agency over the other. It would be nice to see tests that are generalized. Otherwise we're not really asserting that things behave as expected for each agency.

2024-08-08 19:24 UTC, tdooner commented on app/spec/mailers/applicant_mailer_spec.rb
> +    travel_to Time.new(2024, 7, 7)
I brought in a gem for this - `timecop` - in my PR here: https://github.com/DSACMS/iv-cbv-payroll/pull/154

2024-08-08 19:33 UTC, tdooner commented on app/app/models/cbv_flow_invitation.rb
> +  end
See https://github.com/DSACMS/iv-cbv-payroll/pull/154, which implements a very similar method called `expires_at`.

2024-08-08 19:33 UTC, tdooner commented on app/app/views/applicant_mailer/invitation_email.html.erb
> +        <a href=<%= @cbv_flow_invitation.to_url %> class="usa-button width-auto" type="button">
Make sure to put quotes around the URL. Can't leave anything up to chance when it comes to email rendering...

2024-08-08 19:33 UTC, tdooner commented on app/config/locales/en.yml
> +        nyc: HRA
I feel kind of weird about only putting `nyc` here - because we may forget to add `ma` or `sandbox` later. Maybe worth just including those now so we don't forget them later? Idk.

2024-08-08 19:33 UTC, tdooner commented on app/spec/mailers/previews/caseworker_mailer_preview.rb
> +    cbv_flow = CbvFlow.create(case_number: "ABC1234", argyle_user_id: "abc-def-ghi")
argyle_user_id? lol, throwback.

2024-08-09 22:23 UTC, carmenrosalop requested changes
Looking good! Here are a few requests:
- [x] Update the measure of the text to match designs (token 5 or 4 we can pair on this if you'd like) https://designsystem.digital.gov/design-tokens/typesetting/measure/ For reference, the width in px for the text in Figma is 493
- [x]  Remove the "Thank you!" below CTA 
- [x] Text below the line "This is an automatically..." should be smaller than body text from 16px to 14 px.
<img width="751" alt="Screenshot 2024-08-09 at 3 10 53 PM" src="https://github.com/user-attachments/assets/13003ac3-d947-49bb-846a-c2819eb5abae">

2024-08-09 22:37 UTC, tdooner approved these changes

2024-08-09 22:37 UTC, tdooner commented on app/config/locales/en.yml
> +      body_html: We need to verify your income as part of your benefits application, as requested by %{agency_acronym}. This process is unique to you, so please do not share this invitation with anyo
I know the design had it, but, the comma after the deadline date is not grammatically correct.

```suggestion
      body_html: We need to verify your income as part of your benefits application, as requested by %{agency_acronym}. This process is unique to you, so please do not share this invitation with anyone else. <strong>You have until %{deadline} to complete your verification.</strong> Otherwise, you'll need to request a new invitation.
```

2024-08-09 23:01 UTC, carmenrosalop commented
One more thing @allthesignals the spacing between the body and CTA and line below should be [token 5 ](https://designsystem.digital.gov/design-tokens/spacing-units/) or 40px

2024-08-12 18:51 UTC, carmenrosalop approved these changes
LGTM!

2024-08-12 19:45 UTC, merged