Track error events
DSACMS/iv-cbv-payroll pull request #165
Opened 2024-08-13 03:56 UTC by allthesignals

## Ticket

Resolves [1288](https://jiraent.cms.gov/browse/FFS-1288)

## Changes

Adds error event columns and tracks accordingly.

## Context for reviewers

Does not yet handle for these errors.

## Testing

Tested manually using this account: https://docs.pinwheelapi.com/public/docs/sandbox#datanotavailable

2024-08-13 20:53 UTC, tdooner requested changes
Looks good, but please write tests to verify that:
1. The payment details page renders successfully when income data is not available
2. The three `errored_at` timestamps are properly set when a pinwheel webhook returns the corresponding error. AFAIK, we only have seen the error occur with income data, so just a test for that one should at least prevent future regressions, if we're not able to easily write tests for all three.

2024-08-13 20:53 UTC, tdooner commented on app/app/controllers/cbv/payment_details_controller.rb
> +    @employment ? @employment["employer_name"] : I18n.t("cbv.payment_details.show.unknown")
Why not use those fancy new methods here?

```suggestion
    return I18n.t("cbv.payment_details.show.unknown") unless has_employment_data?

    @employment["employer_name"]
```

2024-08-14 19:20 UTC, tdooner commented on app/app/controllers/cbv/payment_details_controller.rb
> +    @employment ? @employment["employer_name"] : I18n.t("cbv.payment_details.show.unknown")
Ah, I didn't consider that. I mean, yeah, it's kind of awkward. (You can always feel free to push back on my suggestions if you think they'll suck, heh.) The most important thing to me is that there is some test coverage of how these pages render with different subsets of data so we don't accidentally break it in the future if we were to improve the way these methods work later.

2024-08-14 20:54 UTC, GeorgeCodes19 commented on app/spec/controllers/cbv/payment_details_controller_spec.rb
> +      PinwheelAccount.create!(
Some recently merged changes now allow us to use a [factory](https://github.com/DSACMS/iv-cbv-payroll/blob/main/app/spec/support/Factories.rb) to create models. 

When you want to use the factory you can simply call the `create` method provided by `FactoryBot`. Example [here](https://github.com/DSACMS/iv-cbv-payroll/blob/main/app/spec/models/cbv_flow_spec.rb#L5)

https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#using-factories

2024-08-15 16:28 UTC, GeorgeCodes19 approved these changes
LGTM

2024-08-15 16:51 UTC, merged

2024-08-15 17:32 UTC, tdooner commented on docs/app/rendered/database-schema.pdf
ah, my bad