Required fields
DSACMS/iv-cbv-payroll pull request #167
Opened 2024-08-13 18:26 UTC by allthesignals

Closes [FFS-1300](https://jiraent.cms.gov/browse/FFS-1300)
## Changes

Adds not null constraint for fields 

## Context for reviewers

For previous fields, provides some default

## Testing

- I've confirmed locally that the data in the `cbv_flows_invitation` table is correct. The application also shows a successful flash notification.
- Users cannot proceed with an invalid date provided in the `snap_application_date` input field due to client-side validation.

![Screenshot 2024-08-14 at 11 27 48 AM](https://github.com/user-attachments/assets/ad7b9c7e-dd19-4fef-ae97-bdeb5f20719e)
![Screenshot 2024-08-14 at 11 31 53 AM](https://github.com/user-attachments/assets/76923819-320c-4082-91fa-2bc939c7aee2)
## Javascript Disabled
![Screenshot 2024-08-14 at 11 37 57 AM](https://github.com/user-attachments/assets/04ca70b2-3ac2-4689-a7dc-1d82e47e671b)
## Required fields for MA
![Screenshot 2024-08-14 at 1 30 07 PM](https://github.com/user-attachments/assets/34e747d3-3a79-4afd-a958-a4e30d497fe6)
## Required fields for NYC
![Screenshot 2024-08-14 at 1 30 07 PM](https://github.com/user-attachments/assets/58ece037-8fe5-4883-af43-5e2544e2bf8d)

2024-08-13 18:42 UTC, GeorgeCodes19 commented on app/db/migrate/20240813181942_require_fields_for_cbv_invitation.rb
> +    change_column_null :cbv_flow_invitations, :client_id_number, false, "Unknown"
Right, I think the CbvFlowInvitation model should be updated to include a new validation

2024-08-13 19:42 UTC, GeorgeCodes19 commented on app/db/migrate/20240813181942_require_fields_for_cbv_invitation.rb
> +    change_column_null :cbv_flow_invitations, :client_id_number, false, "Unknown"
Right. I'm not sure about the Rails-way of doing it, but we should probably keep this as optional. A bunch of tests will fail after this. The alternative would be to handle the required fields in the controller.

2024-08-13 20:15 UTC, GeorgeCodes19 commented on app/db/migrate/20240813181942_require_fields_for_cbv_invitation.rb
> +    change_column_null :cbv_flow_invitations, :client_id_number, false, "Unknown"
Yeah I can it on. I'm nearly done with it, but have a few tests to iron out.

2024-08-13 20:56 UTC, GeorgeCodes19 commented on app/app/models/cbv_flow_invitation.rb
> +  def nyc_site?
Is there a better way of doing this? We can't directly compare in the validator itself due to `site_id` not being defined on the Model. Open to suggestions, but this gets the balling rolling.

2024-08-13 20:56 UTC, GeorgeCodes19 commented on app/db/schema.rb
> +    t.date "snap_application_date", null: false
ehhh... I might walk this back.

2024-08-13 20:56 UTC, GeorgeCodes19 commented on app/spec/models/cbv_flow_spec.rb
> +      first_name: "John",
Lots of code duplication regarding the fields needed to create a `CbvFlowInvitation` without getting an error for missing fields. This should probably be abstracted into a test helper/module

2024-08-13 21:15 UTC, tdooner reviewed
Please fix the migration so it matches `db/schema.rb`.

Also, what is the user-facing behavior like? I don't see any changes to the controllers/views, so I'm assuming it's just going to fail deep down somewhere in the CbvInvitationService with a missing field? Let's make sure there is a good error message.

2024-08-13 21:15 UTC, tdooner commented on app/app/models/cbv_flow_invitation.rb
> +  def nyc_site?
This seems fine to me for now since we only have one page that's creating and modifying CbvFlowInvitation objects.

If we wanted to come up with an abstraction to move the site-specific field validation logic out of the model, a common Rails pattern is a "form object" which is a kind of wrapper of the `params` hash for a specific page, and can handle which fields are displayed and validated (i.e. there could be one form object for the MA form fields and one for the NYC form fields). I'm inclined to say we don't need that level of abstraction yet.

2024-08-13 21:15 UTC, tdooner commented on app/db/schema.rb
> +    t.date "snap_application_date", null: false
Yes - please make sure the migration has a `change_column_null` for `snap_application_date`, or else we will have a different schema between dev/test and production (that'd be bad!)

The migration also allows NULLs for `agency_id_number` field, which seems correct, but unnecessary, since it already allows nulls. So you could remove that line from the migration.

2024-08-13 21:15 UTC, tdooner commented on app/spec/controllers/cbv/entries_controller_spec.rb
> +        snap_application_date: Date.today) }
style nit: Use `do/end` for multiline blocks in Ruby

(e.g.
```ruby 
let(:invitation) do
  CbvFlowInvitation.create!(
    ...
  )
end
```
)

2024-08-13 21:15 UTC, tdooner commented on app/spec/models/cbv_flow_invitation_spec.rb
> +  end
Indenting looks off here

2024-08-13 21:15 UTC, tdooner commented on app/spec/models/cbv_flow_spec.rb
> +      first_name: "John",
Agreed. The Rails-y thing to do is to use the [FactoryBot gem](https://github.com/thoughtbot/factory_bot) which gives you a method (a "factory" method) to create models with default sets of fields. It's quite easy and convenient to work with. We can make a note to implement it next time we add a required field to one of these models.

2024-08-13 21:16 UTC, tdooner requested changes
Actually, I'm gonna use "Request Changes" for the migration/schema comment above, so we don't inadvertently merge it in the current state.

2024-08-14 02:50 UTC, GeorgeCodes19 commented on app/spec/controllers/cbv_flow_invitations/nyc_spec.rb
> +        cbv_flow_invitation: attributes_for(:cbv_flow_invitation, site_id: "nyc", client_id_number: client_id_number, case_number: "ABC1234"),
nit, this could be written a bit more clear

2024-08-14 02:50 UTC, GeorgeCodes19 commented on app/spec/mailers/applicant_mailer_spec.rb
> +  let(:cbv_flow_invitation) { create(:cbv_flow_invitation, email_address: email, site_id: "nyc", client_id_number: "ABC123") }
adding `client_id_number` because the Model validator is actually working and forcing us to pass it when the `site_id` = `nyc`

2024-08-14 02:50 UTC, GeorgeCodes19 commented on app/spec/support/Factories.rb
> +    snap_application_date { Date.today.strftime("%m/%d/%Y") }
Defaulting to the date format that the client will submit e.g. `08/13/2024`. This will ensure that the`before_validation` hook on the `CbvFlowInvitation` model responsible for casting the string to a Date object actually works.

2024-08-14 02:50 UTC, GeorgeCodes19 commented on app/spec/models/cbv_flow_invitation_spec.rb
> +  let(:valid_attributes) do
Could do `attributes_for` here (derived from the `FactoryBot` gem)

2024-08-14 15:13 UTC, GeorgeCodes19 commented on app/spec/models/cbv_flow_spec.rb
> +      first_name: "John",
I opted to use FactoryBot 👍🏾

2024-08-14 15:16 UTC, GeorgeCodes19 commented on app/app/models/cbv_flow_invitation.rb
> +      errors.add(:snap_application_date, "is not a valid date")
Should be `errors`. I'm going to add a test case for this as well.

2024-08-14 18:27 UTC, tdooner approved these changes
LGTM, good work, thank you! Thank you especially for all the screenshots and description of how you tested this.

2024-08-14 18:27 UTC, tdooner commented on app/spec/controllers/cbv_flow_invitations/nyc_spec.rb
> +        cbv_flow_invitation: attributes_for(:cbv_flow_invitation, site_id: "nyc", client_id_number: client_id_number, case_number: "ABC1234"),
Using factories here defeats the point of the test: it seeks to assert that when the form fields from the previous page are POSTed to the `create` endpoint, it actually creates the object. If we use the factory to dynamically include all the proper fields, we lose the fact that the list of params we're passing in here actually matches the form on the previous page.

2024-08-14 18:37 UTC, GeorgeCodes19 commented on app/app/models/cbv_flow_invitation.rb
> +  end
That's good feedback. It remember toying with this for a good 20 minutes until inspected the class with the debugger. Googling didn't really provide any decent approaches.

2024-08-14 18:47 UTC, merged