Agency specific copy and login links for the caseworker entry page
DSACMS/iv-cbv-payroll pull request #188
Opened 2024-08-19 17:58 UTC by GeorgeCodes19

## Ticket

Resolves [FFS-1188](https://jiraent.cms.gov/browse/FFS-1188)

## Changes

- Added a new controller for the caseworkers' entry pages `entries_controller`
- Added test to assert that agency specific copy is rendered when navigating to a specific agency entry page
- Fixed a bug whereas the application's home page had an error for a missing translation.

> Testing instructions, background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.

## Testing

Visually inspected the webpages locally and compared them to the Figma mock.
![Screenshot 2024-08-19 at 1 57 14 PM](https://github.com/user-attachments/assets/940113b8-e9b1-4c68-8e90-eb7b36708a43)
![Screenshot 2024-08-19 at 1 57 02 PM](https://github.com/user-attachments/assets/c75929c6-ecd5-405e-85bf-c70b24c919b2)

2024-08-19 19:08 UTC, GeorgeCodes19 commented on app/app/controllers/caseworker/entries_controller.rb
> +  end
ahh good catch! it's not being used anymore. I was previously passing it to the view, but found it easier to use a new translation entry.

2024-08-19 19:16 UTC, GeorgeCodes19 commented on app/app/views/pages/home.html.erb
> +<% welcome = t("shared.verify.welcome") %>
This fixes the home page title bug.

2024-08-19 19:54 UTC, carmenrosalop requested changes
The copy updates look good! The only thing that needs updating are the headers inside the process list. To align with how we implemented a previous /agreement page, the process list doesn't have headers but instead should have bolded body text like in the [Figma](https://www.figma.com/design/qzbsxwS2wsouKK1JmRtn2H/Consent-Based-Verification?node-id=1897-7643&t=HbXqWrhS8TgJWnkd-4) See images for reference.

![359198150-940113b8-e9b1-4c68-8e90-eb7b36708a43](https://github.com/user-attachments/assets/8ab075df-c6c1-4ba1-9ece-6d3984f038c4)
![Screenshot 2024-08-19 at 12 48 36 PM](https://github.com/user-attachments/assets/bcd93755-0960-4b8c-ba8a-e6f9e5ace1ac)

2024-08-19 22:59 UTC, tdooner approved these changes

2024-08-19 22:59 UTC, tdooner commented on app/app/controllers/caseworker/entries_controller.rb
> +    @current_site = current_site
This should be unnecessary if you rebase on `main` now

2024-08-19 22:59 UTC, tdooner commented on app/config/routes.rb
> +      scope "/:site_id", module: :caseworker do
I think putting it on the `scope` itself is a bit more intuitive - since it's referring to the "site_id" parameter that is specified by `scope "/:site_id"` if you see what I mean? It's kind of weird to have the constraint at a higher level than the scope that defines the variable.

```suggestion
      scope "/:site_id", module: :caseworker, constraints: { site_id: Regexp.union(Rails.application.config.sites.site_ids) } do
```

2024-08-20 18:26 UTC, carmenrosalop approved these changes
Thanks George! LGTM

2024-08-20 19:07 UTC, merged