1354: Display logo on PDFs
DSACMS/iv-cbv-payroll pull request #268
Opened 2024-09-10 18:53 UTC by allthesignals

## Ticket

Resolves [1354](https://jiraent.cms.gov/browse/FFS-1354)

## Changes

Adds the agency logos to the PDFs

## Context for reviewers

Some trickiness with Wicked PDFs using assets. I used the helper that base64 encodes them. The logos are small enough that it probably doesn't matter.

## Testing

<img width="826" alt="Screenshot 2024-09-10 at 2 50 58 PM" src="https://github.com/user-attachments/assets/1d4ad0f6-2aad-46f1-8c50-4fbab7f62094">

<img width="807" alt="Screenshot 2024-09-10 at 2 50 43 PM" src="https://github.com/user-attachments/assets/1020afa7-ea5e-4726-a518-d202d2842dd6">

2024-09-10 18:55 UTC, GeorgeCodes19 approved these changes

2024-09-10 19:16 UTC, tdooner approved these changes

2024-09-10 19:16 UTC, tdooner commented on app/app/views/cbv/summaries/show.pdf.erb
> +  <% end %>
IMHO it would look better to use the "square" version of the logo (those logos have cropped out the agency name so they are a bit more square-shaped). The agency name in the logo is duplicative of the agency name in the title directly following the logo.

The logo filenames are also part of the site config... so you could do:

```suggestion
  <% if current_site?(:ma) %>
    <%= image_tag wicked_pdf_asset_base64(current_site.logo_square_path), class: "text-middle", style: "width: 140px;" %>
  <% elsif current_site?(:nyc) %>
    <%= image_tag wicked_pdf_asset_base64(current_site.logo_square_path), class: "text-middle", style: "width: 170px;" %>
  <% end %>
```

2024-09-10 19:26 UTC, carmenrosalop requested changes
Looks good, but there are two changes that can make it better:
- Can we move the logos to the left of the header?
- And make the "SNAP Income Pilot | Agency name" bold

<img width="690" alt="Screenshot 2024-09-10 at 12 23 36 PM" src="https://github.com/user-attachments/assets/fc6d3740-59f6-4193-887f-1462a715dd1e">

2024-09-11 16:37 UTC, tdooner approved these changes
PNG is a good idea. I left it as AVIF originally with part of my brain wondering whether we were going to see any compatibility issues. I guess so!

2024-09-11 17:07 UTC, carmenrosalop commented
Looks good! Thanks Matt. The logo is in the middle of the header instead of to the left of the heading, but I don't see a problem with it. 
The original logos we got from DTA/HRA came with PNG format.

2024-09-11 17:07 UTC, carmenrosalop approved these changes
LGTM!

2024-09-11 20:18 UTC, merged