George/ffs 1412 input validation
DSACMS/iv-cbv-payroll pull request #281
Opened 2024-09-17 01:13 UTC by GeorgeCodes19

## Ticket

Resolves ([FFS-1412](https://jiraent.cms.gov/browse/FFS-1412))

## Changes

> Added model-level validation for the `CbvFlowInvitation` model
> Added Tests for validation
> Added [`en.yml` translations for Active Record Models](https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models)
> Ignoring these same translations when running `I18n` unused task
> Updated USWDS form helper to support multiple model-level errors. .

## Testing

I tested forms locally and created tests for them. **The test coverage for this feature can be improved. Several areas where increased coverage would benefit:**

- When sending email via AWS fails - There is an exception that is caught and an error informing the case worker that the invitation email could not be delivered to the provided email. Currently it is assumed that this works, but the code has not yet been tested.
- The `datepicker` input could have some client-side validation enforcing the same rules as the model. _I think there may be a Rails way of doing this?_

2024-09-18 15:24 UTC, makaelastephens commented on app/config/locales/en.yml
> +              ma_too_old: Enter today's date or the date you contacted the client. This date must be today or in the past 30 days.
Enter today's date or the date you contacted the client. This date must be today or in the past year.

2024-09-18 18:12 UTC, makaelastephens commented
The content looks right to me!

2024-09-18 23:18 UTC, tdooner requested changes

2024-09-18 23:18 UTC, tdooner commented on app/app/views/caseworker/cbv_flow_invitations/_sandbox.html.erb
> +</div>
Why are all of these surrounded in a `field_with_errors` class? I would expect the UswdsFormBuilder to do that?

2024-09-18 23:18 UTC, tdooner commented on app/app/views/caseworker/cbv_flow_invitations/new.html.erb
> +<% site_id = @cbv_flow_invitation.site_id || @site_id %>
Nice catch - it looks like `@site_id` is only set in the `new` action, not in `create`. It might be better to just initialize the object with the `site_id` attribute, and then we could consistently access this as `@cbv_flow_invitation.site_id`.

E.g. in the `new` action:
```ruby
@cbv_flow_invitation = CbvFlowInvitation.new(site_id: site_id)
```

Not a blocker though. We could do that later.

2024-09-18 23:18 UTC, tdooner commented on app/config/locales/en.yml
> +              invalid_format: must be letters only
Yeah - this validation error can be deleted from the I18n strings since we aren't actually doing that validation anymore.

2024-09-18 23:18 UTC, tdooner commented on app/config/locales/en.yml
> +              nyc_too_old: SNAP application/recertification date must be today or in the past 30 days.
Question for @makaelastephens  - I think the intent of the story is that the error message should say "SNAP application date" in NYC and "SNAP recertification date" in MA. Is that right?

2024-09-18 23:18 UTC, tdooner commented on app/config/locales/en.yml
> -        invite_failed: 'Error sending invitation to %{email_address}: %{error_message}.'
It looks like you renamed this to `invite_error` but might have forgotten to add that string to this file?

2024-09-18 23:18 UTC, tdooner commented on app/spec/factories/cbv_flow_invitation.rb
> +      end
What? This is really complicated... Why is including the provider even necessary? I'd prefer we just inline those `generate_*` methods into the factory, personally, since this is the only file that is using it.

2024-09-18 23:18 UTC, tdooner commented on app/spec/mailers/applicant_mailer_spec.rb
> +      end
This seems like some vestigial code you were using during development? We shouldn't be catching exceptions here in general - rspec will happily tell us if these `let`s have an exception.

2024-09-18 23:18 UTC, tdooner commented on config/locales/en.yml
> +
Looks like this file was inadvertently created. We shouldn't have a top-level `config/locales/en.yml` in the monorepo root.

2024-09-19 13:06 UTC, makaelastephens commented on app/app/models/cbv_flow_invitation.rb
> +  NYC_CLIENT_ID_REGEX = /\A[A-Z]{2}\d{5}[A-Z]\z/
I didn't know we were doing this.

2024-09-19 13:07 UTC, makaelastephens commented on app/app/models/cbv_flow_invitation.rb
> +  NYC_CLIENT_ID_REGEX = /\A[A-Z]{2}\d{5}[A-Z]\z/
I think we might want to see if Casey can test the validation before we merge to prod (NYC eligibility specialist)

2024-09-19 13:08 UTC, makaelastephens commented on app/config/locales/en.yml
> +              nyc_too_old: SNAP application/recertification date must be today or in the past 30 days.
No - DTA changed it.
The field NYC enters is "SNAP application/recertification date"
The field for DTA is "Today's date".

2024-09-19 17:00 UTC, GeorgeCodes19 commented on app/config/locales/en.yml
> +              ma_too_old: Enter today's date or the date you contacted the client. This date must be today or in the past 30 days.
@makaelastephens Looks like after you and I did a review there were some changes that I didn't push. We actually got rid of `ma_too_old ` and `ma_future_date` and kept a single `ma_invalid_date` and `nyc_invalid_date`. 

```suggestion
            snap_application_date:
              invalid_date: is not a valid date
              ma_invalid_date: Enter today's date or the date you contacted the client. This date must be today or in the past year.
              nyc_invalid_date: SNAP application/recertification date must be today or in the past 30 days.
```

2024-09-19 20:27 UTC, GeorgeCodes19 commented on app/spec/factories/cbv_flow_invitation.rb
> +      end
So I've tried a number of different approaches to resolve this. I kept running into: 
`FactoryBot::MethodDefinitionError: Defining methods in blocks (trait or factory) is not supported `

I don't find this approach to be overly complex. I'm actually a fan of how FactoryBot provides hooks and that it's even possible to augment the model instance. In attempt to add methods to the FactoryBot instance I broke 45 tests. So I'm tempted to stick with this unless you have clear direction on how to accomplish this.

2024-09-19 21:54 UTC, tdooner approved these changes
Looks good to me! Thanks for addressing everything I came up with before. The `format_case_number` thing is the last blocker; after fixing that, feel free to merge.

2024-09-19 21:54 UTC, tdooner commented on .githooks/pre-commit
> +fi
Cool, will be interested to try this!

2024-09-19 21:54 UTC, tdooner commented on app/app/controllers/caseworker/cbv_flow_invitations_controller.rb
> +      return render :new
No `return` keyword necessary here.

2024-09-19 21:54 UTC, tdooner commented on app/app/models/cbv_flow_invitation.rb
> +  validates :middle_name, presence: false
I think we could just remove this line since it's not validating anything, right?
```suggestion
```

2024-09-19 21:54 UTC, tdooner commented on app/app/controllers/caseworker/cbv_flow_invitations_controller.rb
> +      redirect_to caseworker_dashboard_path(site_id: params[:site_id])
Sorry I didn't notice this earlier. We need the `return` here or else the logic below will continue executing and we will get an error with the `render :new` (a "double render" error when you try to tell Rails two different things to do with the response).

```suggestion
      return redirect_to caseworker_dashboard_path(site_id: params[:site_id])
```

2024-09-19 21:54 UTC, tdooner commented on app/app/controllers/caseworker/cbv_flow_invitations_controller.rb
> +      return render :new
nitpick: No return keyword is necessary here.

```suggestion
     render :new
```

2024-09-19 21:54 UTC, tdooner commented on app/app/controllers/caseworker/cbv_flow_invitations_controller.rb
> +      :welid
The field is still named `beacon_id` even though it is labeled in the UI as the "WELID", right?

```suggestion
      :beacon_id
```

2024-09-19 21:54 UTC, tdooner commented on app/app/models/cbv_flow_invitation.rb
> +  validates :middle_name, presence: false
We could probably remove this since it's not validating anything, right?
```suggestion
```

2024-09-19 21:54 UTC, tdooner commented on app/spec/mailers/applicant_mailer_spec.rb
> +  let(:valid_agency_id_number) { "1234567" }
It doesn't look like this is being used elsewhere in the test.
```suggestion
```

2024-09-19 21:54 UTC, tdooner commented on app/spec/mailers/caseworker_mailer_spec.rb
> +      expect(email_body).to include("submitted by the client on #{expected_date}")
Interesting. Was this test failing due to the wrong date being in there? Maybe it was another test that implicitly relied on being run before 8pm ET. Thanks for fixing it.

2024-09-19 21:54 UTC, tdooner commented on app/app/models/cbv_flow_invitation.rb
> +      self.case_number = case_number.rjust(12, "0")
This logic still looks wrong to me, please double check before merging.

2024-09-19 23:17 UTC, GeorgeCodes19 commented on app/spec/mailers/caseworker_mailer_spec.rb
> +      expect(email_body).to include("submitted by the client on #{expected_date}")
I was actually seeing date/time differences. Hence why I switched to a different date initializer. `Time.zone.today`

2024-09-19 23:23 UTC, GeorgeCodes19 commented on app/app/controllers/caseworker/cbv_flow_invitations_controller.rb
> +      return render :new
Removing the return here results in a double render

```
AbstractController::DoubleRenderError: Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...); return".

  0) Caseworker::CbvFlowInvitationsController#create requires the ma fields
     Failure/Error: redirect_to caseworker_dashboard_path(site_id: params[:site_id])

     AbstractController::DoubleRenderError:
       Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...); return".
     # ./app/controllers/caseworker/cbv_flow_invitations_controller.rb:46:in `create'
     ```

2024-09-19 23:26 UTC, GeorgeCodes19 commented on app/app/controllers/caseworker/cbv_flow_invitations_controller.rb
> +      return render :new
Removing this return statement results in double render.

2024-09-19 23:33 UTC, merged

2024-09-19 23:35 UTC, tdooner commented on app/app/controllers/caseworker/cbv_flow_invitations_controller.rb
> +      return render :new
My bad, I misread the code. Sorry for the wild goose chase.