1558: Update view logic and language for no paystubs found scenario
DSACMS/iv-cbv-payroll pull request #282
Opened 2024-09-18 19:29 UTC by allthesignals

## Ticket

Resolves [1558](https://jiraent.cms.gov/browse/FFS-1558)

## Changes

 - Adds new language and view logic for when no payments (paystubs are found)
 - Updates the Table ViewComponent to be a little more flexible
 - Adds gpg to the Brewfile

## Context for reviewers

You can test this out with this sandbox login credential: https://docs.pinwheelapi.com/public/docs/sandbox#:~:text=voe_and_voie_available_no_paystubs

Notice that I added a line in the summaries controller which lets you set it to caseworker mode in the development environment only.

Further, **this PR removes the payments presence check! Which could lead to bugs! We should test thoroughly...**

## Testing

The test for this scenario was already written.

<img width="929" alt="image" src="https://github.com/user-attachments/assets/e6b682bd-ce1a-4404-b9bf-e433bb339dea">

<img width="1208" alt="image" src="https://github.com/user-attachments/assets/f0c63c7f-e105-4b14-ad98-5a213823a2c1">

[client.pdf](https://github.com/user-attachments/files/17065366/client.pdf)
[caseworker.pdf](https://github.com/user-attachments/files/17065367/caseworker.pdf)

2024-09-18 22:19 UTC, tdooner approved these changes

2024-09-18 22:19 UTC, tdooner commented on app/spec/controllers/cbv/payment_details_controller_spec.rb
> +        expect(response.body).to include("find any payments from this employer in the past 90 days.")
Lol, yep, ok.

2024-09-19 19:46 UTC, carmenrosalop requested changes
@allthesignals The summary page where we didn't find income should say this message in the blue cell "We didn't find any payments from this employer in the past 90 days." Instead of showing $0
![Screenshot 2024-09-19 at 12 45 05 PM](https://github.com/user-attachments/assets/5ac32354-5e02-414d-b578-099540e6d34c)

2024-09-19 20:19 UTC, tdooner approved these changes
Some ideas for improvement, take them or leave them. No blockers.

2024-09-19 20:19 UTC, tdooner commented on app/app/controllers/cbv/summaries_controller.rb
> +          locals: { is_caseworker: (Rails.env.development? && params[:is_caseworker]) || false },
nit: `|| false` is redundant, logically speaking

Also - if we are going to add logic to spoof being a caseworker in non-production, that's cool, but it might be good to write a test just to verify that it doesn't work in production.

2024-09-19 20:19 UTC, tdooner commented on app/app/controllers/cbv/summaries_controller.rb
> +          payments_grouped_by_employer: summarize_by_employer(@payments, @employments, @incomes, @identities, @cbv_flow.pinwheel_accounts),
Yeah.... definitely worth trying to move this logic into classes during tech debt cleanup.

2024-09-19 20:19 UTC, tdooner commented on app/app/controllers/concerns/cbv/reports_helper.rb
> +          payments: account_payments,
Nice, this is more understandable.

2024-09-19 20:19 UTC, tdooner commented on app/app/views/cbv/summaries/show.html.erb
> +  <%= get_comment_by_account_id(account_id).dig("comment") != "" ? get_comment_by_account_id(account_id).dig("comment") : t("shared.not_applicable") %>
Does this work even when no comment is saved (i.e. is comment `nil` or empty string)? Generally, using `.present?` is better than `!= ""` because it will also be false for `nil`.

2024-09-24 16:16 UTC, carmenrosalop approved these changes
All four pages look good! Payment details, summary and two PDFs. Thanks Matt!

2024-09-24 16:24 UTC, merged