FFS-1561: Add top providers
DSACMS/iv-cbv-payroll pull request #341
Opened 2024-10-30 23:21 UTC by allthesignals

## Ticket

Resolves [1561](https://jiraent.cms.gov/browse/FFS-1561)

## Changes

- Added New Relic events to the `pinwheel_controller.rb` for tracking applicant interaction with top payroll providers and app-based employers
- Added New Relic events to track when a user toggles between payroll and app-based employer blocks on the `employer_searches` page
- Imported new Spanish translations
- Updates the employer searches UI with the top-providers
## Testing

![image](https://github.com/user-attachments/assets/722e3bd0-9f01-486c-baef-9901f4de3c15)
![image](https://github.com/user-attachments/assets/89a69deb-5645-4ef8-a510-738d549ab073)
![image](https://github.com/user-attachments/assets/96f92565-6412-4fc1-9587-a9d554859c06)

HR visible: 

<img width="1407" alt="image" src="https://github.com/user-attachments/assets/42ab495c-29db-4766-9043-517bbb13a7a3">

2024-11-16 00:08 UTC, tdooner requested changes
Blockers:
* Two translations feedback items
* Separating this PR from the Spanish support for invitation emails. I made a ticket to track it: [FFS-2108](https://jiraent.cms.gov/browse/FFS-2108)

2024-11-18 14:39 UTC, GeorgeCodes19 commented on app/app/javascript/controllers/cbv/employer_search.js
> +    return pathMatch ? pathMatch[1] : 'en';
I noticed some weird behavior where it was returning undefined and upon viewing the page results the entire `header` element was missing! It happened a few times, but I couldn't determine why. Since the locale was present in all URLs I figured it would be a good fallback.

2024-11-18 14:41 UTC, GeorgeCodes19 commented on app/app/views/cbv/employer_searches/show.html.erb
> +                alt="A placeholder image"
Yeah I'm getting annoyed with some of this AI stuff. I don't even use co-pilot, but it seems like Cursor does suggest some pretty useless autocomplete recommendations that slip in here and there.

2024-11-18 14:45 UTC, GeorgeCodes19 commented on app/config/locales/es.yml
> +      verify_income_button: Verifique sus ingresos
This was purposefully added. Is it convention that we separate including translations from code in a separate PR? This caused a lot of headaches because some of the translations that we got back didn't appear to be used at all or the keys had changed to a different namespace. It wasn't possible to get all checks passing without addressing missing/wrong translation entries.

2024-11-18 19:11 UTC, GeorgeCodes19 commented on app/app/views/cbv/employer_searches/show.html.erb
> +                alt="A placeholder image"
lol, this can happen when multiple people work on a PR. Thanks for the clarification! I thought my IDE was going rogue.

2024-11-18 19:13 UTC, GeorgeCodes19 commented on app/config/locales/es.yml
> +      verify_income_button: Verifique sus ingresos
`main` was merged in with missing translations. We then received the translations and I figured this ticket would be deemed feature complete with the Spanish translations included. I'll move this elsewhere.

2024-11-19 00:30 UTC, tdooner requested changes

2024-11-19 00:30 UTC, tdooner commented on app/config/locales/en.yml
> +        popular_providers: Or choose from popular payroll providers or apps
Sorry but I think you've gotta take another look at the translations files. These strings are missing their corresponding Spanish versions.

I saw you added them to the `ignore_missing` list, but we should only be using that list when we don't intend to support a certain page.

2024-11-19 16:02 UTC, GeorgeCodes19 commented on app/app/javascript/controllers/cbv/employer_search.js
> +    this.disableButtons()
The locale wasn't defined just yet, but the `trackUserAction` depended on it. So I opted to instantiate the vars ahead of invoking any methods/functions.

2024-11-19 20:11 UTC, tdooner approved these changes

2024-11-19 20:12 UTC, merged