No ticket: deduplicated expired event, refactored ClickedCBVInvitationLink slightly
DSACMS/iv-cbv-payroll pull request #353
Opened 2024-11-15 19:07 UTC by millerti

## Ticket
No ticket. Fixes to work done in [FFS-1839](https://jiraent.cms.gov/browse/FFS-1839)

## Changes
Made ApplicantLinkExpired unique by cbv_flow_id.
Refactored ClickedCBVInvitationLink to its own function to simplify set_cbv_flow.

## Testing
Trigger both changed events and verify that they fire correctly and that the ApplicantLinkExpired event contains a valid cbv_flow_id. 

You can easily expire a link by setting its created_at date to 15.days.ago.

2024-11-15 20:32 UTC, millerti commented on app/app/controllers/cbv/base_controller.rb
> +      session[:cbv_flow_id] = @cbv_flow.id
I moved these lines up so I could use the cbv_flow_id earlier (line 22). But the unit tests that touch the expired events page explicitly test that session[:cbv_flow_id] is unchanged, and of course now it has changed. So I wonder: is there some important reason to test this and I'm breaking something unintentionally by having the session[:cbv_flow_id] set on the expired page? Or was this just something we could conveniently unit test, and I can get rid of it?

2024-11-15 23:15 UTC, tdooner requested changes

2024-11-15 23:15 UTC, tdooner commented on app/app/controllers/cbv/base_controller.rb
> +      cbv_flow_id: cbv_flow_id,
Looks like you're passing in the invitation's ID into the method, but calling it `cbv_flow_id`. I'd recommend passing in both as you've done in the other methods.

2024-11-21 00:42 UTC, tdooner approved these changes

2024-11-21 00:43 UTC, tdooner commented on app/app/controllers/cbv/base_controller.rb
> +      cbv_flow_id: cbv_flow_id,
Ah true, there is no cbv_flow_id if the invitation is expired. The invitation_id is great, thanks.

2024-11-21 13:35 UTC, merged