FFS-1555: Various
DSACMS/iv-cbv-payroll pull request #373
Opened 2024-11-25 22:29 UTC by millerti

## [FFS-1555](https://jiraent.cms.gov/browse/FFS-1555)

## Changes
Two small fixes to copy:
1. On the Caseworker Invite page, the wording about the date now differs by state.
2. On the Client PDF for MA, we now specify DTA where we didn't before.

## Testing
1. In MA, NYC, and Sandbox, navigate to the Caseworker Invite page and make sure that this sentence has been updated as proposed in the ticket:
![image](https://github.com/user-attachments/assets/d1c26c41-7562-4f0f-af17-0b41f57505fc)

2. Access the Income Verification Report PDF and verify that the agency's short name is now used instead of saying "your SNAP agency":
![image](https://github.com/user-attachments/assets/7ee2349c-772a-46db-9af4-b059fe9c54f3)

2024-11-26 00:42 UTC, tdooner requested changes

2024-11-26 00:42 UTC, tdooner commented on app/config/locales/en.yml
> +          sandbox: "<p>Provide some details about the client so we can send them a link to verify their pay information. We'll request the past %{pay_income_days} days of income, based on the client'
Side note, but I think for these site-specific strings where we have only one customization, we should use the "default" key along with whichever site required the customization. E.g. in this case

```suggestion
        description_html:
          default: "<p>Provide some details about the client so we can send them a link to verify their pay information. We'll request the past %{pay_income_days} days of income, based on the client's application/recertification date.</p><p>If multiple members of the household earn income, send an invite link to each household member.</p>"
          ma: "<p>Provide some details about the client so we can send them a link to verify their pay information. We'll request the past %{pay_income_days} days of income, based on today's date.</p><p>If multiple members of the household earn income, send an invite link to each household member.</p>"

```

2024-11-26 00:42 UTC, tdooner commented on app/config/locales/en.yml
> +              sandbox: We have collected your income information with your consent and sent it to your SNAP agency. Any additional income that you weren't able to add to this report should be shared
I'm trying to spot the difference here - is it just "your SNAP agency" vs "%{agency_acronym}"? Even sandbox has an agency acronym, so you could just make the string take that variable in all cases. It would read a bit weird in sandbox ("shared separately with CBV") but that's ok.

The more strings we keep as non-site-specific, the happier our translation process will be (and the easier it is to maintain), so slight bias towards keeping this non-site-specific if possible. (We can still use the variable in a non-site-specific string, to be clear)

2024-11-26 00:42 UTC, tdooner commented on app/app/views/cbv/summaries/show.pdf.erb
> +  <p><%= t(".pdf.client.description", agency_acronym: current_site.agency_short_name) %></p>
Whoops:
<img width="1072" alt="image" src="https://github.com/user-attachments/assets/faba1530-a4be-4e20-b58d-d4e14d89335f">

Either take my suggestion below to keep it a non-site-specific translation, or:

```suggestion
  <p><%= site_translation(".pdf.client.description", agency_acronym: current_site.agency_short_name) %></p>
```

2024-11-26 13:52 UTC, millerti commented on app/config/locales/en.yml
> +              sandbox: We have collected your income information with your consent and sent it to your SNAP agency. Any additional income that you weren't able to add to this report should be shared
I think you're right, taking this suggestion.

2024-12-03 01:08 UTC, tdooner approved these changes
Looks good, thanks for fixing:

<img width="1076" alt="image" src="https://github.com/user-attachments/assets/ad58c293-d600-44ff-b6ac-d73cc1b9d571">

2024-12-03 15:22 UTC, merged